
export const FETCH_GENRES_REQUEST = 'FETCH_GENRES_REQUEST';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const FETCH_GENRES_FAILURE = 'FETCH_GENRES_FAILURE';


export const FETCH_MOVIEDETAILS_REQUEST = 'FETCH_MOVIEDETAILS_REQUEST';
export const FETCH_MOVIEDETAILS_SUCCESS = 'FETCH_MOVIEDETAILS_SUCCESS';
export const FETCH_MOVIEDETAILS_FAILURE = 'FETCH_MOVIEDETAILS_FAILURE';

export const FETCH_ALLMOVIES_REQUEST = 'FETCH_ALLMOVIES_REQUEST';
export const FETCH_ALLMOVIES_SUCCESS = 'FETCH_ALLMOVIES_SUCCESS';
export const FETCH_ALLMOVIES_FAILURE = 'FETCH_ALLMOVIES_FAILURE';


export const FETCH_GENRESDATA_REQUEST = 'FETCH_GENRESDATA_REQUEST';
export const FETCH_GENRESDATA_SUCCESS = 'FETCH_GENRESDATA_SUCCESS';
export const FETCH_GENRESDATA_FAILURE = 'FETCH_GENRESDATA_FAILURE';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';


export const ADD_USER= 'ADD_USER';
export const REMOVE_USER='REMOVE_USER';

export   const token='eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmNTc0N2FhY2RiMGY5NGMzZDZmYWQxMmJmN2QzNGQzMCIsIm5iZiI6MTcyMDU1MTM1NS45NTQzODQsInN1YiI6IjY0YjRlYTAyZTBjYTdmMDE0NDJhZTFhMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.j6h_wbXPT3AD16sbuIdk-lagOdThRgSCLHcm4t03dQM'

export const BaseURL='https://image.tmdb.org/t/p/w500';